# Generated by Django 3.1.2 on 2020-10-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201013_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team'},
        ),
    ]
