# Generated by Django 3.1.2 on 2020-10-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Teams'},
        ),
    ]
