# Generated by Django 3.1.2 on 2020-10-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201015_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-id',)},
        ),
    ]
