# Generated by Django 3.1.2 on 2020-10-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20201015_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',)},
        ),
    ]
